=== jdmar3/digital-hegemony/new-data/securegrants.neh.gov/Open/data/Schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "$ref": "#/definitions/object_02",
  "definitions": {
    "object_01": {
      "type": "object",
      "required": [
        "@type",
        "title",
        "accessLevel",
        "accrualPeriodicity",
        "contactPoint",
        "describedBy",
        "describedByType",
        "description",
        "identifier",
        "issued",
        "keyword",
        "landingPage",
        "modified",
        "publisher",
        "distribution",
        "bureauCode",
        "programCode",
        "theme"
      ],
      "additionalProperties": false,
      "properties": {
        "@type": {
          "type": "string"
        },
        "title": {
          "type": "string"
        },
        "accessLevel": {
          "type": "string"
        },
        "accrualPeriodicity": {
          "type": "string"
        },
        "contactPoint": {
          "title": "contactPoint",
          "type": "object",
          "required": [
            "@type",
            "fn",
            "hasEmail"
          ],
          "additionalProperties": false,
          "properties": {
            "@type": {
              "type": "string"
            },
            "fn": {
              "type": "string"
            },
            "hasEmail": {
              "type": "string"
            }
          }
        },
        "describedBy": {
          "type": "string"
        },
        "describedByType": {
          "type": "string"
        },
        "description": {
          "type": "string"
        },
        "identifier": {
          "type": "string"
        },
        "issued": {
          "type": "string"
        },
        "keyword": {
          "$ref": "#/definitions/array_01"
        },
        "landingPage": {
          "type": "string"
        },
        "modified": {
          "type": "string"
        },
        "publisher": {
          "title": "publisher",
          "type": "object",
          "required": [
            "@type",
            "name"
          ],
          "additionalProperties": false,
          "properties": {
            "@type": {
              "type": "string"
            },
            "name": {
              "type": "string"
            }
          }
        },
        "distribution": {
          "type": "array",
          "title": "distribution",
          "items": {
            "type": "object",
            "required": [
              "@type",
              "downloadURL",
              "mediaType",
              "format",
              "title",
              "describedBy",
              "describedByType"
            ],
            "additionalProperties": false,
            "properties": {
              "@type": {
                "type": "string"
              },
              "downloadURL": {
                "type": "string"
              },
              "mediaType": {
                "type": "string"
              },
              "format": {
                "type": "string"
              },
              "title": {
                "type": "string"
              },
              "describedBy": {
                "type": "string"
              },
              "describedByType": {
                "type": "string"
              }
            }
          }
        },
        "bureauCode": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "programCode": {
          "type": "array",
          "items": {
            "type": "string"
          }
        },
        "theme": {
          "type": "array",
          "items": {
            "type": "string"
          }
        }
      }
    },
    "object_02": {
      "description": "JSON Schema generated by XMLSpy v2016 (http://www.altova.com)",
      "type": "object",
      "required": [
        "conformsTo",
        "describedBy",
        "@context",
        "@type",
        "dataset"
      ],
      "additionalProperties": false,
      "properties": {
        "conformsTo": {
          "type": "string"
        },
        "describedBy": {
          "type": "string"
        },
        "@context": {
          "type": "string"
        },
        "@type": {
          "type": "string"
        },
        "dataset": {
          "type": "array",
          "title": "dataset",
          "items": {
            "$ref": "#/definitions/object_01"
          }
        }
      }
    },
    "array_01": {
      "type": "array",
      "title": "keyword",
      "description": "tuple type",
      "additionalItems": false,
      "minItems": 6,
      "maxItems": 6,
      "items": [
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        },
        {
          "type": "string"
        }
      ]
    }
  }
}

=== jdmar3/digital-hegemony/data/securegrants.neh.gov/Open/data/data.json
{
	"conformsTo": "https://project-open-data.cio.gov/v1.1/schema",
	"describedBy": "https://project-open-data.cio.gov/v1.1/schema/catalog.json",
	"@context": "https://project-open-data.cio.gov/v1.1/schema/catalog.jsonld",
	"@type": "dcat:Catalog",
	"dataset": [
		{
			"@type": "dcat:Dataset",
			"title": "NEH evaluators, 1970-present",
			"accessLevel": "public",
			"accrualPeriodicity": "R/P1M",
			"contactPoint": {
				"@type": "vcard:Contact",
				"fn": "Peter Losin",
				"hasEmail": "mailto:plosin@neh.gov"
			},
			"describedBy": "http://www.neh.gov/open/data/NEH_EvaluatorsDictionary.pdf",
			"describedByType": "application/pdf",
			"description": "NEH peer-review evaluators, 1970-present",
			"identifier": "evaluators",
			"issued": "2015-02-20",
			"keyword": [
				"culture", "history", "humanities", "languages", "literature", "philosophy"
			],
			"landingPage": "http://www.neh.gov/open/data",
			"modified": "2015-02-20",
			"publisher": {
				"@type": "org:Organization",
				"name": "NEH"
			},
			"distribution": [
				{
					"@type": "dcat:Distribution",
					"downloadURL": "http://www.neh.gov/open/data/NEH_Evaluators.zip",
					"mediaType": "application/x-7z-compressed",
					"format": "xml",
					"title": "NEH evaluators",
					"describedBy": "http://www.neh.gov/open/data/NEH_EvaluatorsDictionary.pdf",
					"describedByType": "application/pdf"
				}
			],
			"bureauCode": [
				"418:00"
			],
			"programCode": [
				"010:000"
			],
			"theme": [
				"humanities grants"
			]
		}, {
			"@type": "dcat:Dataset",
			"title": "NEH grant data, 1970-1979",
			"accessLevel": "public",
			"accrualPeriodicity": "R/P1M",
			"contactPoint": {
				"@type": "vcard:Contact",
				"fn": "Peter Losin",
				"hasEmail": "mailto:plosin@neh.gov"
			},
			"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
			"describedByType": "application/pdf",
			"description": "Grants made by NEH, fiscal years 1970-1979",
			"identifier": "Grants-1970s",
			"issued": "2015-02-20",
			"keyword": [
				"culture", "history", "humanities", "journal literature", "languages", "philosophy"
			],
			"landingPage": "http://www.neh.gov/open/data",
			"modified": "2015-02-20",
			"publisher": {
				"@type": "org:Organization",
				"name": "NEH"
			},
			"distribution": [
				{
					"@type": "dcat:Distribution",
					"downloadURL": "http://www.neh.gov/open/data/NEH_Grants1970s.zip",
					"mediaType": "application/x-7z-compressed",
					"format": "xml",
					"title": "NEH grants, 1970-1979",
					"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
					"describedByType": "application/pdf"
				}
			],
			"bureauCode": [
				"418:00"
			],
			"programCode": [
				"010:000"
			],
			"theme": [
				"humanities grants"
			]
		}, {
			"@type": "dcat:Dataset",
			"title": "NEH grant data, 1980-1989",
			"accessLevel": "public",
			"accrualPeriodicity": "R/P1M",
			"contactPoint": {
				"@type": "vcard:Contact",
				"fn": "Peter Losin",
				"hasEmail": "mailto:plosin@neh.gov"
			},
			"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
			"describedByType": "application/pdf",
			"description": "Grants made by NEH, fiscal years 1980-1989",
			"identifier": "grants-1980s",
			"issued": "2015-02-20",
			"keyword": [
				"culture", "history", "humanities", "languages", "literature", "philosophy"
			],
			"landingPage": "http://www.neh.gov/open/data",
			"modified": "2015-02-20",
			"publisher": {
				"@type": "org:Organization",
				"name": "NEH"
			},
			"distribution": [
				{
					"@type": "dcat:Distribution",
					"downloadURL": "http://www.neh.gov/open/data/NEH_Grants1980s.zip",
					"mediaType": "application/x-7z-compressed",
					"format": "XML",
					"title": "NEH grants, 1980s",
					"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
					"describedByType": "application/pdf"
				}
			],
			"bureauCode": [
				"418:00"
			],
			"programCode": [
				"010:000"
			],
			"theme": [
				"humanities grants"
			]
		}, {
			"@type": "dcat:Dataset",
			"title": "NEH grant data, 1990-1999",
			"accessLevel": "public",
			"accrualPeriodicity": "R/P1M",
			"contactPoint": {
				"@type": "vcard:Contact",
				"fn": "Peter Losin",
				"hasEmail": "mailto:plosin@neh.gov"
			},
			"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
			"describedByType": "application/pdf",
			"description": "Grants made by NEH, fiscal years 1990-1999",
			"identifier": "grants-1990s",
			"issued": "2015-02-20",
			"keyword": [
				"culture", "history", "humanities", "languages", "literature", "philosophy"
			],
			"landingPage": "http://www.neh.gov/open/data",
			"modified": "2015-02-20",
			"publisher": {
				"@type": "org:Organization",
				"name": "NEH"
			},
			"distribution": [
				{
					"@type": "dcat:Distribution",
					"downloadURL": "http://www.neh.gov/open/data/NEH_Grants1990s.zip",
					"mediaType": "application/x-7z-compressed",
					"format": "XML",
					"title": "NEH grants, 1990s",
					"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
					"describedByType": "application/pdf"
				}
			],
			"bureauCode": [
				"418:00"
			],
			"programCode": [
				"010:000"
			],
			"theme": [
				"humanities grants"
			]
		}, {
			"@type": "dcat:Dataset",
			"title": "NEH grant data, 2000-2009",
			"accessLevel": "public",
			"accrualPeriodicity": "R/P1M",
			"contactPoint": {
				"@type": "vcard:Contact",
				"fn": "Peter Losin",
				"hasEmail": "mailto:plosin@neh.gov"
			},
			"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
			"describedByType": "application/pdf",
			"description": "Grants made by NEH, fiscal years 2000-2009",
			"identifier": "grants-2000s",
			"issued": "2015-02-20",
			"keyword": [
				"culture", "history", "humanities", "languages", "literature", "philosophy"
			],
			"landingPage": "http://www.neh.gov/open/data",
			"modified": "2015-02-20",
			"publisher": {
				"@type": "org:Organization",
				"name": "NEH"
			},
			"distribution": [
				{
					"@type": "dcat:Distribution",
					"downloadURL": "http://www.neh.gov/open/data/NEH_Grants2000s.zip",
					"mediaType": "application/x-7z-compressed",
					"format": "xml",
					"title": "NEH grants, 2000s",
					"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
					"describedByType": "application/pdf"
				}
			],
			"bureauCode": [
				"418:00"
			],
			"programCode": [
				"010:000"
			],
			"theme": [
				"humanities grants"
			]
		}, {
			"@type": "dcat:Dataset",
			"title": "NEH grant data, 2010-2019",
			"accessLevel": "public",
			"accrualPeriodicity": "R/P1M",
			"contactPoint": {
				"@type": "vcard:Contact",
				"fn": "Peter Losin",
				"hasEmail": "mailto:plosin@neh.gov"
			},
			"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
			"describedByType": "application/pdf",
			"description": "Grants made by NEH, fiscal years 2010-2019",
			"identifier": "grants-2010s",
			"issued": "2015-02-20",
			"keyword": [
				"culture", "history", "humanities", "languages", "literature", "philosophy"
			],
			"landingPage": "http://www.neh.gov/open/data",
			"modified": "2015-02-20",
			"publisher": {
				"@type": "org:Organization",
				"name": "NEH"
			},
			"distribution": [
				{
					"@type": "dcat:Distribution",
					"downloadURL": "http://www.neh.gov/open/data/NEH_Grants2010s.zip",
					"mediaType": "application/x-7z-compressed",
					"format": "xml",
					"title": "NEH grants, 2010s",
					"describedBy": "http://www.neh.gov/open/data/NEH_GrantsDictionary.pdf",
					"describedByType": "application/pdf"
				}
			],
			"bureauCode": [
				"418:00"
			],
			"programCode": [
				"010:000"
			],
			"theme": [
				"humanities grants"
			]
		}
	]
}
